title: Fresh Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: overflow
palette: blue
header:
  title: Fresh
  tagline: Header Tagline
  profile_img: images/avatar.png
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: '&copy; Fresh. All rights reserved.'
  links:
    - text: Made with
      url: 'https://www.stackbit.com'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
